sudo: required
services:
  - docker

before_install:
 - docker build -t npotta/react-test -f ./client/Dockerfile.dev ./client
 
script:
 - docker run npotta/react-test npm test -- --coverage

after_success:
 - docker build -t npotta/multi-client ./client
 - docker build -t npotta/multi-nginx ./nginx
 - docker build -t npotta/multi-server ./server
 - docker build -t npotta/multi-worker ./worker

  # login to docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" -password-stdin
 - docker push npotta/multi-client
 - docker push npotta/multi-nginx
 - docker push npotta/multi-server
 - docker push npotta/multi-worker
 