sudo: required
services:
  - docker

before_install:
 - docker build -t npotta/react-test -f ./client/Dockerfile.dev ./client
 
script:
 - docker run npotta/react-test npm test -- --coverage

after_success:
 - docker build -t npotta/multi-client ./client
 - docker build -t npotta/multi-nginx ./nginx
 - docker build -t npotta/multi-server ./server
 - docker build -t npotta/multi-worker ./worker

  # login to docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push npotta/multi-client
 - docker push npotta/multi-nginx
 - docker push npotta/multi-server
 - docker push npotta/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker-new
  env: MultiDockerNew-env
  bucket_name: elasticbeanstalk-us-east-1-826212554276
  bucket_path: docker-multi-new
on:
  branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: 
  secure: $AWS_SECRET_KEY